import { ZodiacSign, LunarMansion } from '../types/astronomy';

export const ZODIAC_SIGNS: ZodiacSign[] = [
  { name: 'الحمل', symbol: '♈', season: 'ناري | أوائل الربيع', element: 'ناري', startDeg: 0 },
  { name: 'الثور', symbol: '♉', season: 'ترابي | أواسط الربيع', element: 'ترابي', startDeg: 30 },
  { name: 'الجوزاء', symbol: '♊', season: 'هوائي | أواخر الربيع', element: 'هوائي', startDeg: 60 },
  { name: 'السرطان', symbol: '♋', season: 'مائي | أوائل الصيف', element: 'مائي', startDeg: 90 },
  { name: 'الأسد', symbol: '♌', season: 'ناري | أواسط الصيف', element: 'ناري', startDeg: 120 },
  { name: 'السنبلة', symbol: '♍', season: 'ترابي | أواخر الصيف', element: 'ترابي', startDeg: 150 },
  { name: 'الميزان', symbol: '♎', season: 'هوائي | أوائل الخريف', element: 'هوائي', startDeg: 180 },
  { name: 'العقرب', symbol: '♏', season: 'مائي | أواسط الخريف', element: 'مائي', startDeg: 210 },
  { name: 'القوس', symbol: '♐', season: 'ناري | أواخر الخريف', element: 'ناري', startDeg: 240 },
  { name: 'الجدي', symbol: '♑', season: 'ترابي | أوائل الشتاء', element: 'ترابي', startDeg: 270 },
  { name: 'الدلو', symbol: '♒', season: 'هوائي | أواسط الشتاء', element: 'هوائي', startDeg: 300 },
  { name: 'الحوت', symbol: '♓', season: 'مائي | أواخر الشتاء', element: 'مائي', startDeg: 330 },
];

export const LUNAR_MANSIONS: LunarMansion[] = [
  { index: 1, name: 'الشَّرَطَين', startDeg: 0 },
  { index: 2, name: 'البُطَين', startDeg: 12.857 },
  { index: 3, name: 'الثُّرَيّا', startDeg: 25.714 },
  { index: 4, name: 'الدَّبَران', startDeg: 38.571 },
  { index: 5, name: 'الهَقْعَة', startDeg: 51.428 },
  { index: 6, name: 'الهَنْعَة', startDeg: 64.285 },
  { index: 7, name: 'الذِّراع', startDeg: 77.142 },
  { index: 8, name: 'النَّثْرَة', startDeg: 90.0 },
  { index: 9, name: 'الطَّرْف', startDeg: 102.857 },
  { index: 10, name: 'الجَبْهَة', startDeg: 115.714 },
  { index: 11, name: 'الزُّبْرَة', startDeg: 128.571 },
  { index: 12, name: 'الصَّرْفَة', startDeg: 141.428 },
  { index: 13, name: 'العَوَّاء', startDeg: 154.285 },
  { index: 14, name: 'السِّماك الأعزل', startDeg: 167.142 },
  { index: 15, name: 'الغَفْر', startDeg: 180.0 },
  { index: 16, name: 'الزُّبانَى', startDeg: 192.857 },
  { index: 17, name: 'الإكْليل', startDeg: 205.714 },
  { index: 18, name: 'القَلْب', startDeg: 218.571 },
  { index: 19, name: 'الشَّوْلَة', startDeg: 231.428 },
  { index: 20, name: 'النَّعائِم', startDeg: 244.285 },
  { index: 21, name: 'البَلْدَة', startDeg: 257.142 },
  { index: 22, name: 'سَعْد الذّابِح', startDeg: 270.0 },
  { index: 23, name: 'سَعْد بُلَع', startDeg: 282.857 },
  { index: 24, name: 'سَعْد السُّعود', startDeg: 295.714 },
  { index: 25, name: 'سَعْد الأَخْبِية', startDeg: 308.571 },
  { index: 26, name: 'فَرْغ الدَّلْو المقدَّم', startDeg: 321.428 },
  { index: 27, name: 'فَرْغ الدَّلْو المؤخَّر', startDeg: 334.285 },
  { index: 28, name: 'الرِّشاء (بَطْن الحوت)', startDeg: 347.142 },
];
